### ISSUE TITLE
Documentation uses argument that Flatpak 0.8.9 doesn't recognize

### ISSUE THREAD

**Issue by jeremiah** [flatpak/flat-manager#18]
In this document: https://github.com/flatpak/flat-manager in the README it states;

`flatpak-builder --install-deps-from=flathub --repo=local-repo builddir org.gnome.eog.yml`

but when I run this command flatpak-builder states "Option parsing failed: Unknown option --install-deps-from=flathub" 

Do I need a newer flatpak-builder?

**Comment by oleid** [comment]
You can work-around that by not using that option.

As a side note: I noticed today, that you need  `>=flatpak-1.3` since the sever calls it with the option `-no-update-summary`, which was introduced in `1.3`.

You can build, however, flatpak 1.3.4 from `debian/experimental` on `debian/stable` when installing the `build-dep` from `stretch-backports` and adjust `debian/control` to merely depend on 
 - gobject-introspection 1.50.0
 - libostree 2019.1

**Comment by jeremiah** [comment]
Thanks for the suggestion. I ended up going with packages from stretch-backports and it worked well. I'll send a documentation patch as a PR for those on Debian systems.

**Comment by oleid** [comment]
Really? flatpak from backports (as of last week) was too old for me, as it's missing a command line option I mentioned above. I only found it observing the logs when uploading /publishing new builds using flat-manager-client.

Hopefully flatpak 1.4 hits backports soon, now that it's released.
