### ISSUE TITLE
Question: Does the flat-manager-client have a size limitations?

### ISSUE THREAD

**Issue by jakobjakobson13** [flatpak/flat-manager#22]
Dear developers,

The flatpak-image of the texlive distribution [org.freedesktop.Sdk.Extension.texlive](https://github.com/flathub/org.freedesktop.Sdk.Extension.texlive) seems to fail not in the building phase but in the uploading phase, see also [Log](https://flathub.org/builds/#/builders/10/builds/801/steps/15/logs/stdio). The flatpak package should be pretty big (download size around 1.5 GB, installation size around 3.2 GB).
So could this be a problem for the flat-manager?

Regards

Jakob

**Comment by barthalion** [comment]
This took a while but will be fixed by changes in `wip/async-objects-upload`. The requests library always ends up reading entire file, causing the overflow error. This is already deployed on cncf-x86-1 and cncf-x86-2 builders and will land on all builders after I finish the work and it passes Alex' review.
